// product Data
export const productData = [
  {
    id: 1,
    category: "Computers and Laptops",
    name: "MacBook pro M2 chipset 256gb ssd 8gb ram space-gray color with apple 1 year warranty",
    description:
      "Product details are a crucial part of any eCommerce website or online marketplace. These details help the potential customers to make an informed decision about the product they are interested in buying. A well-written product description can also be a powerful marketing tool that can help to increase sales.Product details typically include information about the product's features, specifications, dimensions, weight, materials, and other relevant information that can help customers to understand the product better. The product details section should also include high-quality images and videos of the product, as well as customer reviews and ratings.",
    image_Url: [
      {
        public_id: "test",
        url: "https://www.istorebangladesh.com/images/thumbs/0000286_macbook-pro-m1_550.png",
      },
      {
        public_id: "test",
        url: "https://www.istorebangladesh.com/images/thumbs/0000286_macbook-pro-m1_550.png",
      },
    ],
    shop: {
      name: "Apple inc.",
      shop_avatar: {
        public_id: "test",
        url: "https://www.hatchwise.com/wp-content/uploads/2022/05/amazon-logo-1024x683.png",
      },
      ratings: 4.2,
    },
    price: 999,
    discount: 20,
    rating: 4,
    total_sell: 35,
    stock: 10,
  },
  {
    id: 2,
    category: "Mobile and Tablets",
    name: "Iphone 14 pro max 256 gb ssd and 8 gb ram silver colour",
    description:
      "Product details are a crucial part of any eCommerce website or online marketplace. These details help the potential customers to make an informed decision about the product they are interested in buying. A well-written product description can also be a powerful marketing tool that can help to increase sales.Product details typically include information about the product's features, specifications, dimensions, weight, materials, and other relevant information that can help customers to understand the product better. The product details section should also include high-quality images and videos of the product, as well as customer reviews and ratings.",
    image_Url: [
      {
        public_id: "test",
        url: "https://m.media-amazon.com/images/I/31Vle5fVdaL.jpg",
      },
      {
        public_id: "test",
        url: "https://m.media-amazon.com/images/I/31Vle5fVdaL.jpg",
      },
    ],
    shop: {
      name: "Amazon Ltd",
      shop_avatar: {
        public_id: "test",
        url: "https://www.hatchwise.com/wp-content/uploads/2022/05/amazon-logo-1024x683.png",
      },
      ratings: 4.2,
    },
    price: 809,
    discount: 100,
    rating: 5,
    total_sell: 80,
    stock: 10,
    category: "Mobile & Tablets",
  },
  {
    id: 1,
    category: "Computers and Laptop",
    name: "MacBook pro M2 chipset 256gb ssd 8gb ram space gray color with apple 1 year warranty",
    description:
      "Product details are a crucial part of any eCommerce website or online marketplace. These details help the potential customers to make an informed decision about the product they are interested in buying. A well-written product description can also be a powerful marketing tool that can help to increase sales.Product details typically include information about the product's features, specifications, dimensions, weight, materials, and other relevant information that can help customers to understand the product better. The product details section should also include high-quality images and videos of the product, as well as customer reviews and ratings.",
    image_Url: [
      {
        public_id: "test",
        url: "https://www.istorebangladesh.com/images/thumbs/0000286_macbook-pro-m1_550.png",
      },
      {
        public_id: "test",
        url: "https://www.istorebangladesh.com/images/thumbs/0000286_macbook-pro-m1_550.png",
      },
    ],
    shop: {
      name: "Apple inc.",
      shop_avatar: {
        public_id: "test",
        url: "https://www.hatchwise.com/wp-content/uploads/2022/05/amazon-logo-1024x683.png",
      },
      ratings: 4.2,
    },
    price: 1099,
    discount: 50,
    rating: 4,
    total_sell: 75,
    stock: 10,
    category: "Computers & Laptop",
  },
  {
    id: 4,
    category: "Others",
    name: "New Fashionable Watch for men 2023 with multiple colors",
    description:
      "Product details are a crucial part of any eCommerce website or online marketplace. These details help the potential customers to make an informed decision about the product they are interested in buying. A well-written product description can also be a powerful marketing tool that can help to increase sales.Product details typically include information about the product's features, specifications, dimensions, weight, materials, and other relevant information that can help customers to understand the product better. The product details section should also include high-quality images and videos of the product, as well as customer reviews and ratings.",
    image_Url: [
      {
        public_id: "test",
        url: "https://i0.wp.com/eccocibd.com/wp-content/uploads/2022/01/1802NL02_1.png?fit=550%2C550&ssl=1",
      },
      {
        public_id: "test",
        url: "https://i0.wp.com/eccocibd.com/wp-content/uploads/2022/01/1802NL02_1.png?fit=550%2C550&ssl=1",
      },
    ],
    shop: {
      name: "Shahriar Watch House",
      shop_avatar: {
        public_id: "test",
        url: "https://www.hatchwise.com/wp-content/uploads/2022/05/amazon-logo-1024x683.png",
      },
      ratings: 4.2,
      category: "Others",
    },
    price: 1000,
    discount: 79,
    rating: 4,
    total_sell: 12,
    stock: 10,
  },
  {
    id: 5,
    category: "Shoes",
    name: "New Trend shoes for gents with all sizes",
    description:
      "Product details are a crucial part of any eCommerce website or online marketplace. These details help the potential customers to make an informed decision about the product they are interested in buying. A well-written product description can also be a powerful marketing tool that can help to increase sales.Product details typically include information about the product's features, specifications, dimensions, weight, materials, and other relevant information that can help customers to understand the product better. The product details section should also include high-quality images and videos of the product, as well as customer reviews and ratings.",
    image_Url: [
      {
        public_id: "test",
        url: "https://mirzacdns3.s3.ap-south-1.amazonaws.com/cache/catalog/RLV0015/2-800x800.jpg",
      },
      {
        public_id: "test",
        url: "https://mirzacdns3.s3.ap-south-1.amazonaws.com/cache/catalog/RLV0015/2-800x800.jpg",
      },
    ],
    shop: {
      name: "Alisha Shoes Mart",
      shop_avatar: {
        public_id: "test",
        url: "https://www.hatchwise.com/wp-content/uploads/2022/05/amazon-logo-1024x683.png",
      },
      ratings: 4.2,
    },
    price: 120,
    discount: 0,
    rating: 5,
    total_sell: 49,
    stock: 10,
    category: "Shoes",
  },
  {
    id: 1,
    name: "Gaming Headphone Asus with mutiple color and free delivery",
    description:
      "Product details are a crucial part of any eCommerce website or online marketplace. These details help the potential customers to make an informed decision about the product they are interested in buying. A well-written product description can also be a powerful marketing tool that can help to increase sales.Product details typically include information about the product's features, specifications, dimensions, weight, materials, and other relevant information that can help customers to understand the product better. The product details section should also include high-quality images and videos of the product, as well as customer reviews and ratings.",
    image_Url: [
      {
        public_id: "test",
        url: "https://www.startech.com.bd/image/cache/catalog/headphone/havit/h763d/h763d-02-500x500.jpg",
      },
      {
        public_id: "test",
        url: "https://eratablet.com/wp-content/uploads/2022/08/H51ba6537405f4948972e293927673546u.jpg",
      },
    ],
    shop: {
      name: "Asus Ltd",
      shop_avatar: {
        public_id: "test",
        url: "https://www.hatchwise.com/wp-content/uploads/2022/05/amazon-logo-1024x683.png",
      },
      ratings: 4.2,
    },
    price: 300,
    discount: 29,
    rating: 4.5,
    reviews: [
      {
        user: {
          // user object will be here
        },
        comment: "IT's so cool!",
        rating: 5,
      },
    ],
    total_sell: 20,
    stock: 10,
    category: "Music and Gaming",
  },
  {
    id: 4,
    name: "New Fashionable Watch for men 2023 with multiple colors",
    description:
      "Product details are a crucial part of any eCommerce website or online marketplace. These details help the potential customers to make an informed decision about the product they are interested in buying. A well-written product description can also be a powerful marketing tool that can help to increase sales.Product details typically include information about the product's features, specifications, dimensions, weight, materials, and other relevant information that can help customers to understand the product better. The product details section should also include high-quality images and videos of the product, as well as customer reviews and ratings.",
    image_Url: [
      {
        public_id: "test",
        url: "https://i0.wp.com/eccocibd.com/wp-content/uploads/2022/01/1802NL02_1.png?fit=550%2C550&ssl=1",
      },
      {
        public_id: "test",
        url: "https://i0.wp.com/eccocibd.com/wp-content/uploads/2022/01/1802NL02_1.png?fit=550%2C550&ssl=1",
      },
    ],
    shop: {
      name: "Shahriar Watch House",
      shop_avatar: {
        public_id: "test",
        url: "https://www.hatchwise.com/wp-content/uploads/2022/05/amazon-logo-1024x683.png",
      },
      ratings: 4.2,
    },
    price: 100,
    discount: 0,
    rating: 4,
    total_sell: 62,
    stock: 10,
  },
  {
    id: 1,
    name: "Gaming Headphone Asus with mutiple color and free delivery",
    description:
      "Product details are a crucial part of any eCommerce website or online marketplace. These details help the potential customers to make an informed decision about the product they are interested in buying. A well-written product description can also be a powerful marketing tool that can help to increase sales.Product details typically include information about the product's features, specifications, dimensions, weight, materials, and other relevant information that can help customers to understand the product better. The product details section should also include high-quality images and videos of the product, as well as customer reviews and ratings.",
    image_Url: [
      {
        public_id: "test",
        url: "https://www.startech.com.bd/image/cache/catalog/headphone/havit/h763d/h763d-02-500x500.jpg",
      },
      {
        public_id: "test",
        url: "https://eratablet.com/wp-content/uploads/2022/08/H51ba6537405f4948972e293927673546u.jpg",
      },
    ],
    shop: {
      name: "Asus Ltd",
      shop_avatar: {
        public_id: "test",
        url: "https://www.hatchwise.com/wp-content/uploads/2022/05/amazon-logo-1024x683.png",
      },
      ratings: 4.2,
    },
    price: 300,
    discount: 0,
    rating: 4.5,
    reviews: [
      {
        user: {
          // user object will be here
        },
        comment: "IT's so cool!",
        rating: 5,
      },
    ],
    total_sell: 20,
    stock: 10,
  },
  {
    id: 2,
    category: "Mobile and Tablets",
    name: "Iphone 14 pro max 256 gb ssd and 8 gb ram silver colour",
    description:
      "Product details are a crucial part of any eCommerce website or online marketplace. These details help the potential customers to make an informed decision about the product they are interested in buying. A well-written product description can also be a powerful marketing tool that can help to increase sales.Product details typically include information about the product's features, specifications, dimensions, weight, materials, and other relevant information that can help customers to understand the product better. The product details section should also include high-quality images and videos of the product, as well as customer reviews and ratings.",
    image_Url: [
      {
        public_id: "test",
        url: "https://m.media-amazon.com/images/I/31Vle5fVdaL.jpg",
      },
      {
        public_id: "test",
        url: "https://m.media-amazon.com/images/I/31Vle5fVdaL.jpg",
      },
    ],
    shop: {
      name: "Amazon Ltd",
      shop_avatar: {
        public_id: "test",
        url: "https://www.hatchwise.com/wp-content/uploads/2022/05/amazon-logo-1024x683.png",
      },
      ratings: 4.2,
    },
    price: 1099,
    discount: 0,
    rating: 5,
    total_sell: 20,
    stock: 10,
  },
  {
    id: 1,
    category: "Music and Gaming",
    name: "Gaming Headphone Asus with mutiple color and free delivery",
    description:
      "Product details are a crucial part of any eCommerce website or online marketplace. These details help the potential customers to make an informed decision about the product they are interested in buying. A well-written product description can also be a powerful marketing tool that can help to increase sales.Product details typically include information about the product's features, specifications, dimensions, weight, materials, and other relevant information that can help customers to understand the product better. The product details section should also include high-quality images and videos of the product, as well as customer reviews and ratings.",
    image_Url: [
      {
        public_id: "test",
        url: "https://www.startech.com.bd/image/cache/catalog/headphone/havit/h763d/h763d-02-500x500.jpg",
      },
      {
        public_id: "test",
        url: "https://eratablet.com/wp-content/uploads/2022/08/H51ba6537405f4948972e293927673546u.jpg",
      },
    ],
    shop: {
      name: "Asus Ltd",
      shop_avatar: {
        public_id: "test",
        url: "https://www.hatchwise.com/wp-content/uploads/2022/05/amazon-logo-1024x683.png",
      },
      ratings: 4.2,
    },
    price: 300,
    discount: 0,
    rating: 4.5,
    reviews: [
      {
        user: {
          // user object will be here
        },
        comment: "IT's so cool!",
        rating: 5,
      },
    ],
    total_sell: 20,
    stock: 10,
  },
];

// const products = [
//   {
//     _id: 1,
//     name: "American Garden Mushroom Whole Can 425g",
//     weight: "425g",
//     img: "https://i.ibb.co/P9LTCPS/1-b.jpg",
//     price: 175,
//     off: 20,
//     brand: "Wilson",
//     category: "Men's Fashion",
//     size: ["XL", "L", "M", "S", "XS"],
//     stock: "12",
//     numOfReviews: "23",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 2,
//     name: "Arm & Hammer Tropical Paradise",
//     weight: "125g",
//     img: "https://i.ibb.co/0ZnXMJT/2.jpg",
//     price: 200,
//     off: 0,
//     stock: "12",
//     brand: "Wilson",
//     category: "Men's Fashion",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 3,
//     name: "Aloe Vera Leaf each",
//     img: "https://i.ibb.co/RSwfbWM/2-b.jpg",
//     weight: "325g",
//     price: 250,
//     off: 10,
//     stock: "12",
//     brand: "Wilson",
//     category: "Men's Fashion",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "12",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 4,
//     name: "Avocado Juice Fruit Vegetable",
//     weight: "625g",
//     img: "https://i.ibb.co/8rhmZ5b/3.jpg",
//     price: 300,
//     off: 0,
//     stock: "12",
//     brand: "Wilson",
//     category: "Men's Fashion",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 5,
//     name: "Alshifa Natural Honey 250gm",
//     weight: "55g",
//     img: "https://i.ibb.co/ZL1zCW7/3-b.jpg",
//     price: 500,
//     off: 30,
//     stock: "12",
//     brand: "Wilson",
//     category: "Men's Fashion",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "120",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 45,
//     name: "Testy Carrot for Vegetables",
//     weight: "725g",
//     img: "https://i.ibb.co/0DXSdbb/4.jpg",
//     price: 700,
//     off: 10,
//     stock: "12",
//     brand: "Wilson",
//     category: "Men's Fashion",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 6,
//     name: "Mini Pumpkin Box each",
//     weight: "255g",
//     img: "https://i.ibb.co/DGN025D/4-b.jpg",
//     price: 800,
//     off: 0,
//     stock: "12",
//     brand: "Wilson",
//     category: "Men's Fashion",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 7,
//     name: "Tide Detergent, Fresh Scent 100oz",
//     weight: "2325g",
//     img: "https://i.ibb.co/KsYjVLJ/5.jpg",
//     price: 900,
//     off: 0,
//     stock: "12",
//     brand: "Wilson",
//     category: "Men's Fashion",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 8,
//     name: "Shefa'a Natural Honey 250g",
//     weight: "1125g",
//     img: "https://i.ibb.co/xG7VN1J/5-b.jpg",
//     price: 100,
//     off: 50,
//     stock: "12",
//     brand: "Wilson",
//     category: "Men's Fashion",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "100",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 9,
//     name: "Cerelac Wheat Apple Cornflakes 400gm",
//     weight: "125g",
//     img: "https://i.ibb.co/gmPJX6Z/6-b.jpg",
//     price: 450,
//     off: 0,
//     stock: "12",
//     brand: "Wilson",
//     category: "Men's Fashion",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 10,
//     name: "Dabur Honey 250g",
//     weight: "125g",
//     img: "https://i.ibb.co/Qp21sty/7.jpg",
//     price: 175,
//     off: 20,
//     brand: "Levono",
//     category: "Women's Fashion",
//     size: ["XL", "L", "M", "S", "XS"],
//     stock: "12",
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 11,
//     name: "Fresh Wild King Salmon Steak 1lb",
//     weight: "425g",
//     img: "https://i.ibb.co/s9NxJZK/8.jpg",
//     price: 200,
//     off: 0,
//     stock: "12",
//     brand: "Levono",
//     category: "Women's Fashion",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 12,
//     name: "Green Leaf Lettuce 500g",
//     weight: "425g",
//     img: "https://i.ibb.co/YfqDF23/9.jpg",
//     price: 200,
//     off: 10,
//     stock: "12",
//     brand: "Levono",
//     category: "Women's Fashion",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 13,
//     name: "Beef Chuck Steak 1lb",
//     weight: "925g",
//     img: "https://i.ibb.co/Mp1790Q/10.jpg",
//     price: 300,
//     off: 0,
//     stock: "12",
//     brand: "Levono",
//     category: "Women's Fashion",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 14,
//     name: "Ahold Acorn Squash 1piecep<",
//     weight: "425g",
//     img: "https://i.ibb.co/g6WT1b2/11.jpg",
//     price: 500,
//     off: 30,
//     stock: "12",
//     brand: "Levono",
//     category: "Women's Fashion",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 15,
//     name: "CP Chicken Patty 500g",
//     weight: "545g",
//     img: "https://i.ibb.co/7jHtYQQ/12.jpg",
//     price: 700,
//     off: 10,
//     stock: "12",
//     brand: "Levono",
//     category: "Women's Fashion",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 16,
//     name: "Denim Black After Shave 100ml",
//     weight: "425g",
//     img: "https://i.ibb.co/j892ZQs/13.jpg",
//     price: 800,
//     off: 0,
//     stock: 12,
//     brand: "Levono",
//     category: "Women's Fashion",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 17,
//     name: "Mandarin Clementine 22lb",
//     weight: "425g",
//     img: "https://i.ibb.co/6vjkVDM/14.jpg",
//     price: 900,
//     off: 0,
//     stock: "12",
//     brand: "Levono",
//     category: "Women's Fashion",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 18,
//     name: "Calabaza Squash Package each",
//     weight: "425g",
//     img: "https://i.ibb.co/HP5fF01/15.jpg",
//     price: 100,
//     off: 50,
//     stock: "12",
//     brand: "Levono",
//     category: "Women's Fashion",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 19,
//     name: "Testy Carrot for Vegetablesh",
//     weight: "425g",
//     img: "https://i.ibb.co/wLGQ5Fx/16.jpg",
//     price: 450,
//     off: 0,
//     stock: 12,
//     brand: "Levono",
//     category: "Women's Fashion",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 20,
//     name: "Mini Pumpkin Box each",
//     weight: "425g",
//     img: "https://i.ibb.co/9cwggjd/17.jpg",
//     price: 175,
//     off: 0,
//     brand: "PatPat",
//     category: "Computer electronics",
//     size: ["XL", "L", "M", "S", "XS"],
//     stock: "12",
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 21,
//     name: "Tide Detergent, Fresh Scent 100oz",
//     weight: "425g",
//     img: "https://i.ibb.co/sp4kSMc/18.jpg",
//     price: 200,
//     off: 0,
//     stock: 0,
//     brand: "PatPat",
//     category: "Computer electronics",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 22,
//     name: "Tide Detergent, Fresh Scent 100oz",
//     weight: "125g",
//     img: "https://i.ibb.co/w4Hdx3H/19.jpg",
//     price: 50,
//     off: 0,
//     stock: "12",
//     brand: "PatPat",
//     category: "Computer electronics",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 23,
//     name: "hefa'a Natural Honey 250g",
//     weight: "225g",
//     img: "https://i.ibb.co/vhx6Tng/20.jpg",
//     price: 300,
//     off: 0,
//     stock: 12,
//     brand: "PatPat",
//     category: "Computer electronics",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 24,
//     name: "Cerelac Wheat Apple Cornflakes 400gm<",
//     weight: "825g",
//     img: "https://i.ibb.co/SJNhrN3/21.jpg",
//     price: 500,
//     off: 0,
//     stock: "12",
//     brand: "PatPat",
//     category: "Computer electronics",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 25,
//     name: "Dabur Honey 250g",
//     weight: "325g",
//     img: "https://i.ibb.co/Mcv1dpF/22.jpg",
//     price: 900,
//     off: 0,
//     stock: "12",
//     brand: "PatPat",
//     category: "Computer electronics",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 26,
//     name: " Fresh Wild King Salmon Steak 1lb",
//     weight: "425g",
//     img: "https://i.ibb.co/khd9QDb/23.jpg",
//     price: 800,
//     off: 0,
//     stock: 2,
//     brand: "PatPat",
//     category: "Computer electronics",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 27,
//     name: " Strawberries Package 2.25oz",
//     weight: "425g",
//     img: "https://i.ibb.co/ccm2WTK/24.jpg",
//     price: 900,
//     off: 0,
//     stock: 12,
//     brand: "PatPat",
//     category: "Computer electronics",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 28,
//     name: "Green Leaf Lettuce 500g",
//     weight: "825g",
//     img: "https://i.ibb.co/r26KqRq/25.jpg",
//     price: 100,
//     off: 50,
//     stock: "12",
//     brand: "PatPat",
//     category: "Computer electronics",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 29,
//     name: "Beef Chuck Steak 1lb",
//     weight: "125g",
//     img: "https://i.ibb.co/Q70qGWm/26.jpg",
//     price: 450,
//     off: 0,
//     stock: 12,
//     brand: "PatPat",
//     category: "Computer electronics",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },

//   {
//     _id: 30,
//     name: "Cerelac Wheat Apple Cornflakes 400gm<",
//     weight: "625g",
//     img: "https://i.ibb.co/vxhPry2/27.jpg",
//     price: 500,
//     off: 30,
//     stock: "12",
//     brand: "PatPat",
//     category: "Computer electronics",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 31,
//     name: "Mandarin Clementine 22lb",
//     weight: "425g",
//     img: "https://i.ibb.co/cTrw4Kn/28.jpg",
//     price: 700,
//     off: 10,
//     stock: "12",
//     brand: "PatPat",
//     category: "Computer electronics",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 32,
//     name: " Denim Black After Shave 100ml",
//     weight: "425g",
//     img: "https://i.ibb.co/P9S9jRL/29.jpg",
//     price: 800,
//     off: 0,

//     stock: 12,
//     brand: "PatPat",
//     category: "Computer electronics",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 33,
//     name: " Strawberries Package 2.25oz",
//     weight: "525g",
//     img: "https://i.ibb.co/ZxNr0Cr/30.jpg",
//     price: 900,
//     off: 0,

//     brand: "PatPat",
//     category: "Computer electronics",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 34,
//     name: "CP Chicken Patty 500g",
//     weight: "425g",
//     img: "https://i.ibb.co/ZYSHtcD/31.jpg",
//     price: 100,
//     off: 50,
//     stock: "12",
//     brand: "PatPat",
//     category: "Computer electronics",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
//   {
//     _id: 35,
//     name: "Ahold Acorn Squash 1piece",
//     weight: "425g",
//     img: "https://i.ibb.co/b67xGT6/32.jpg",
//     price: 450,
//     off: 0,

//     stock: "12",
//     brand: "PatPat",
//     category: "Computer electronics",
//     size: ["XL", "L", "M", "S", "XS"],
//     numOfReviews: "123",
//     description:
//       "Proactively provide access to cross-platform outsourcing whereas market positioning process improvements. Completely iterate accurate process improvements rather than value-added manufactured products. Conveniently whiteboard rather than multidisciplinary alignments. Progressively initiate interactive architectures rather than plug-and-play imperatives. Competently create user friendly imperatives and high standards in strategic theme areas. Rapidiously drive sustainable systems via focused human capital.",
//   },
// ];

// export default products;
